debug: true
eureka:
    client:
        serviceUrl:
            defaultZone:  http://localhost:9761/eureka/
server:
    servlet: 
        context-path: /
    port: 10082
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: web-manager
    redis:
        host: localhost
        port: 6379
        database: 1
        jedis: 
            pool:
                max-active: 2
    session: 
        store-type: redis #HAZELCAST
    #boot:
        #admin:
            #url: http://localhost:9999
            #context-path: /monitorui
security:
    oauth2:
        client:
            client-id: acme
            client-secret: acmesecret
            scope: read,write
            auto-approve-scopes: '.*'
        authorization:
            checkToken-access: isAuthenticated()
            
jfish:
    session: 
        strategy: customizable
    security:
        sync-permissionData: true
        csrf:
            disable: true
        logout-url: /logout
        alwaysUse-default-target-url: false
        ignoring-urls: /**/captcha**
        cookie: 
            path: ${server.servlet.contextPath}
    plugin: 
        web-admin: 
            captcha: 
                enabled: true
                salt: ASDFA@GUythsdgasdf37890fghjkltyhj
                color: 255, 0, 0
site:
    image-server: 
        base-path: ${server.servlet.contextPath}/images
    upload:
        store-type: LOCAL
        #ftpServer: 127.0.0.1
        #ftpUser: test
        #ftpPassword: test
        file-store-path: G:/temp/upload_files
        app-context-dir: manager
        access-path-patterns: /images/**
        #maxUploadSize: 1024
