spring:
    profiles:
        active: @{env}
    freemarker:
        suffix: .html
    groovy: 
        template: 
            enabled: false
jfish: 
    profile: true
site:
    name: 后台管理系统
    config:
        security:
            preventXssRequest: true