spring:
    profiles:
        active: #{env}
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        validation-query: SELECT 1
        tomcat: 
            test-on-borrow: true
            test-on-return: true
            max-active: 50
            max-wait: 10000
    freemarker:
        suffix: .html
    groovy: 
        template: 
            enabled: false
jfish: 
    profile: true
site:
    name: 后台管理系统
    config:
        security:
            preventXssRequest: true