server:
    port: 9081
spring: 
    datasource: 
        url: jdbc:mysql://localhost:3306/web_admin?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    application:
        name: web-manager
            
jfish:
    security:
        syncPermissionData: false
        csrf:
            disable: true
        logoutUrl: /logout
        # redis: 
            # hostName: 127.0.0.1
    site:
        uploadImageAccessPath: http://localhost/img/manager
        upload:
            #storeType: ftp
            #ftpServer: 127.0.0.1
            #ftpUser: test
            #ftpPassword: test
            fileStorePath: G:/temp/upload_files
            appContextDir: manager
            #maxUploadSize: 1024
